# August Complex Fire (California 229-317)
[ANIMATE1]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h09v03'
    year = 2020
    doys = [247, 248]
    hours = [15, 24]
    remove = 'False'
    name = "august_complex_fire"


# Santiam Fire (Oregon 252-345)
[ANIMATE2]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h09v02'
    year = 2020
    doys = [257, 258]
    hours = [15, 23]
    remove = 'True'
    name = "santiam_fire"

# Pearl Hill Fire (Washington 251-349)
[ANIMATE3]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h09v01'
    year = 2020
    doys = [265, 266]
    hours = [15, 23]
    remove = 'True'
    name = "pearl_hill_fire"

# Hurricane Laura (Cuba 235-237)
[ANIMATE4]
    collection = '/nex/datapool/geonex/public/GOES16/GEONEX-L1G/'
    sensor = 'G16'
    tile = 'h17v06'
    year = 2020
    doys = [235, 236]
    hours = [15, 23]
    remove = 'True'
    name = "hurricane_laura"


# Hurricane Sally (Florida 256-258)
[ANIMATE5]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h16v05'
    year = 2020
    doys = [255, 256]
    hours = [15, 22]
    remove = 'True'
    name = "hurricane_sally"


# Tropical Storm Beta (Texas 256-258)
[ANIMATE6]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h14v05'
    year = 2020
    doys = [263, 264]
    hours = [14, 24]
    remove = 'True'
    name = "tropical_storm_beta"
