# Satellite Configuration File
#                                                                            (REQUIRED)
# [SAMPLE_FORMAT]
#    collection = 'SATELLITE/DATA/PATH'  # path toGeomNEX data                    X
#    sensor = 'GXX'                      # corresponding sensor                   X
#    tile = 'h09v04'                     # tile to retrieve  [Global Grid System] X
#    year = 2021                         # year of interest                       X
#    doys = [247,248]                    # day range of interest [exclusive]      X
#    hours = [12, 22]                    # hour rang of interest [inclusive 24]   X
#    remove = 'False'                    # remove png images after animation      X


[ANIMATE]
    collection = '/nex/datapool/geonex/public/GOES17/GEONEX-L1G/'
    sensor = 'G17'
    tile = 'h09v03'
    year = 2020
    doys = [247, 248]
    hours = [14, 24]
    remove = 'False'
